-- Generated by scripts/gen-taxonomy-seed.js from
-- content/taxonomy/csec_2027_taxonomy_seed.json. Do not hand-edit — re-run
-- the generator instead.

insert into modules (syllabus_code, module_no, name, paper01_items, paper02_marks, weighted_marks, duration_hours)
values
  ('V2027', 1, 'Fundamentals of Secondary Level Mathematics', 20, 30, 100, 65),
  ('V2027', 2, 'Intermediate Secondary Level Mathematics', 20, 30, 100, 65),
  ('V2027', 3, 'Higher Concepts in Secondary Level Mathematics', 20, 30, 100, 65);

insert into topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks
)
values
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 1), 1, 'M1-T1', 'Number Theory and Computation', 1, 4, 'Number Theory and Computation, Consumer Arithmetic (9 marks combined)', null),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 1), 2, 'M1-T2', 'Consumer Arithmetic', 2, 4, 'Number Theory and Computation, Consumer Arithmetic (9 marks combined)', null),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 1), 3, 'M1-T3', 'Sets', 3, 3, 'Introduction to Graphs, Sets, Measurement, Algebra 1 (12 marks combined)', 3),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 1), 4, 'M1-T4', 'Measurement', 4, 4, 'Introduction to Graphs, Sets, Measurement, Algebra 1 (12 marks combined)', 3),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 1), 5, 'M1-T5', 'Algebra 1', 5, 3, 'Introduction to Graphs, Sets, Measurement, Algebra 1 (12 marks combined)', 3),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 1), 6, 'M1-T6', 'Introduction To Graphs', 6, 2, 'Introduction to Graphs, Sets, Measurement, Algebra 1 (12 marks combined)', 3),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 2), 1, 'M2-T1', 'Statistics 1', 7, 4, null, 6),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 2), 2, 'M2-T2', 'Algebra 2', 8, 4, 'Algebra 2, Relations Functions and Graphs 1 (12 marks combined)', 6),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 2), 3, 'M2-T3', 'Relations, Functions and Graphs 1', 9, 4, 'Algebra 2, Relations Functions and Graphs 1 (12 marks combined)', 6),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 2), 4, 'M2-T4', 'Geometry and Trigonometry 1', 10, 4, null, 9),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 2), 5, 'M2-T5', 'Vectors and Matrices 1', 11, 4, null, 3),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 3), 1, 'M3-T1', 'Statistics 2', 12, 4, null, 6),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 3), 2, 'M3-T2', 'Relations, Functions and Graphs 2', 13, 6, null, 6),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 3), 3, 'M3-T3', 'Geometry and Trigonometry 2', 14, 6, null, 9),
  ('V2027', (select id from modules where syllabus_code = 'V2027' and module_no = 3), 4, 'M3-T4', 'Vectors and Matrices 2', 15, 4, null, 9);
